#!/usr/bin/env tsx
/**
 * Headless evidence ladder runner (M2–M5).
 *
 * Usage:
 *   npm run evidence
 *   npm run evidence -- --n 2
 *   npm run evidence -- --write
 *   npm run evidence -- --milestones m2,m4 --write
 *
 * Default output: evidence/_smoke/ (gitignored) so smoke runs do not clobber
 * committed evidence/m2…m5 artifacts. Pass --write / --commit-artifacts to
 * refresh the committed tree (or --out DIR for an explicit path).
 * Observational only — not scientific closure.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  armProtocolMeta,
  EVIDENCE_DEFAULT_N,
  exportArmCsv,
  exportArmJsonl,
  runEvidenceMatrix,
  validateEvidenceMatrix,
  type EvidenceMilestone,
} from "../src/sim/evidence-matrix.ts";
import { evidenceDirPair, resolveEvidenceOutDir } from "./evidence-out-guard.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");

const { evidenceRoot: committedEvidenceDir, smokeRoot: smokeEvidenceDir } = evidenceDirPair(repoRoot);

function parseArgs(argv: string[]) {
  let n: number | undefined;
  let outDir: string | undefined;
  let milestones: EvidenceMilestone[] | undefined;
  let csv = true;
  let writeCommitted = false;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--n" && argv[i + 1]) {
      n = Number(argv[++i]);
    } else if (a === "--out" && argv[i + 1]) {
      outDir = resolve(repoRoot, argv[++i]);
    } else if (a === "--milestones" && argv[i + 1]) {
      milestones = argv[++i].split(",").map((s) => s.trim()) as EvidenceMilestone[];
    } else if (a === "--no-csv") {
      csv = false;
    } else if (a === "--write" || a === "--commit-artifacts") {
      writeCommitted = true;
    } else if (a === "--help" || a === "-h") {
      console.log(
        "Usage: tsx scripts/run-evidence.ts [--n N] [--out DIR] [--milestones m2,m3,m4,m5] [--write|--commit-artifacts] [--no-csv]\n" +
          "Default out: evidence/_smoke (gitignored). Use --write to refresh committed evidence/{m2..m5}. Subpaths like evidence/m2 also require --write.",
      );
      process.exit(0);
    }
  }
  try {
    outDir = resolveEvidenceOutDir({
      outDir,
      writeCommitted,
      evidenceRoot: committedEvidenceDir,
      smokeRoot: smokeEvidenceDir,
    });
  } catch (err) {
    console.error(err instanceof Error ? err.message : err);
    process.exit(2);
  }
  return { n, outDir, milestones, csv, writeCommitted };
}

function folderReadme(milestone: EvidenceMilestone): string {
  return `# Evidence ${milestone.toUpperCase()}

Observational batch artifacts from \`npm run evidence\`.

- Protocol metadata is the first JSONL line (prefix \`# \`).
- Eng scaffolding ≠ scientific closure.
- Protocol-calibrated observational K; no life / autopoiesis claims.
- Smoke default: \`npm run evidence\` → \`evidence/_smoke/\`. Refresh committed: \`npm run evidence -- --write\`.
`;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const validated = validateEvidenceMatrix();
  if (!validated.ok) {
    console.error("evidence matrix invalid:", validated.error);
    process.exit(1);
  }

  console.log(
    `Running evidence matrix n=${args.n ?? EVIDENCE_DEFAULT_N} milestones=${(args.milestones ?? ["m2", "m3", "m4", "m5"]).join(",")} → ${args.outDir}`,
  );

  const started = Date.now();
  const results = runEvidenceMatrix({
    n: args.n,
    milestones: args.milestones,
    collectSeries: false,
    onArm: (arm, index, total) => {
      const meta = armProtocolMeta(arm);
      console.log(`[${index + 1}/${total}] ${meta.armId} n=${meta.n} … ok`);
    },
  });

  const topReadme = `# Homeosys evidence artifacts

Generated by \`npm run evidence\` / \`tsx scripts/run-evidence.ts\`.

## Important

- **Engineering scaffolding ≠ scientific closure.** These runs are observational exports of the M2–M5 ladder.
- **Protocol-calibrated observational K** (densityMin/densityMax from unregulated M2 baseline+envNoControl; see \`src/sim/calibrated-k.ts\`). Not scientific closure.
- **No life / autopoiesis / cognition claims.**
- Default CLI writes \`evidence/_smoke/\` (gitignored). Committed \`evidence/{m2..m5}\` only with \`--write\`.

## Layout

- \`m2/\` — baseline / env-no-control / homeostatic (shared pulse schedule; grids 48×36 + 72×54)
- \`m3/\` — homeostatic vs ultrastable (shared sustained schedule; both grids); UltraEpisodeLog aggregates in summaries
- \`m4/\` — SetpointError vs ViabilityBand (\`abControllerProtocols\`; both grids)
- \`m5/\` — Central | Local | Coordinated | Coordinated α=0 ablation (\`abcOrganizationProtocols\`; both grids). VSM = hypothesis only.

Seed strategy: fixed explicit \`EVIDENCE_SEED_KEYS\` list (N=20) in \`src/sim/evidence-matrix.ts\` — no silent seedKey+i.

See \`docs/evidence/README.md\` for full reproduce notes.
`;

  mkdirSync(args.outDir, { recursive: true });
  writeFileSync(join(args.outDir, "README.md"), topReadme, "utf8");

  for (const arm of results) {
    const dir = join(args.outDir, arm.arm.milestone);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, "README.md"), folderReadme(arm.arm.milestone), "utf8");
    const stem = arm.arm.id;
    writeFileSync(join(dir, `${stem}.jsonl`), exportArmJsonl(arm), "utf8");
    if (args.csv) {
      writeFileSync(join(dir, `${stem}.csv`), exportArmCsv(arm), "utf8");
    }
  }

  const elapsed = ((Date.now() - started) / 1000).toFixed(1);
  console.log(`Wrote ${results.length} arms under ${args.outDir} in ${elapsed}s`);
}

main();
