#!/usr/bin/env tsx
/**
 * Headless evidence ladder runner (M2–M5).
 *
 * Usage:
 *   npm run evidence
 *   npm run evidence -- --n 2
 *   npm run evidence -- --milestones m2,m4 --out evidence
 *
 * Writes JSONL (+ CSV) under evidence/m2/ … evidence/m5/ with a protocol
 * metadata header. Observational only — not scientific closure.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  armProtocolMeta,
  exportArmCsv,
  exportArmJsonl,
  runEvidenceMatrix,
  validateEvidenceMatrix,
  type EvidenceMilestone,
} from "../src/sim/evidence-matrix.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");

function parseArgs(argv: string[]) {
  let n: number | undefined;
  let outDir = join(repoRoot, "evidence");
  let milestones: EvidenceMilestone[] | undefined;
  let csv = true;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--n" && argv[i + 1]) {
      n = Number(argv[++i]);
    } else if (a === "--out" && argv[i + 1]) {
      outDir = resolve(repoRoot, argv[++i]);
    } else if (a === "--milestones" && argv[i + 1]) {
      milestones = argv[++i].split(",").map((s) => s.trim()) as EvidenceMilestone[];
    } else if (a === "--no-csv") {
      csv = false;
    } else if (a === "--help" || a === "-h") {
      console.log(`Usage: tsx scripts/run-evidence.ts [--n N] [--out DIR] [--milestones m2,m3,m4,m5] [--no-csv]`);
      process.exit(0);
    }
  }
  return { n, outDir, milestones, csv };
}

function folderReadme(milestone: EvidenceMilestone): string {
  return `# Evidence ${milestone.toUpperCase()}

Observational batch artifacts from \`npm run evidence\`.

- Protocol metadata is the first JSONL line (prefix \`# \`).
- Eng scaffolding ≠ scientific closure.
- Provisional K unchanged; no life / autopoiesis claims.
- Reproduce from repo root: \`npm run evidence\`
`;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const validated = validateEvidenceMatrix();
  if (!validated.ok) {
    console.error("evidence matrix invalid:", validated.error);
    process.exit(1);
  }

  console.log(
    `Running evidence matrix n=${args.n ?? 10} milestones=${(args.milestones ?? ["m2", "m3", "m4", "m5"]).join(",")}`,
  );

  const started = Date.now();
  const results = runEvidenceMatrix({
    n: args.n,
    milestones: args.milestones,
    collectSeries: false,
    onArm: (arm, index, total) => {
      const meta = armProtocolMeta(arm);
      console.log(`[${index + 1}/${total}] ${meta.armId} n=${meta.n} … ok`);
    },
  });

  const topReadme = `# Homeosys evidence artifacts

Generated by \`npm run evidence\` / \`tsx scripts/run-evidence.ts\`.

## Important

- **Engineering scaffolding ≠ scientific closure.** These runs are observational exports of the M2–M5 ladder.
- **Provisional K** (densityMin/densityMax) is unchanged from lab defaults.
- **No life / autopoiesis / cognition claims.**

## Layout

- \`m2/\` — baseline vs homeostatic (shared pulse schedule)
- \`m3/\` — homeostatic vs ultrastable (shared sustained / nonstationary schedule); UltraEpisodeLog aggregates in summaries
- \`m4/\` — SetpointError vs ViabilityBand (\`abControllerProtocols\`)
- \`m5/\` — Central | Local | Coordinated (\`abcOrganizationProtocols\`)

Seed strategy: fixed \`EVIDENCE_SEED_KEYS\` list in \`src/sim/evidence-matrix.ts\`.

See \`docs/evidence/README.md\` for full reproduce notes.
`;

  mkdirSync(args.outDir, { recursive: true });
  writeFileSync(join(args.outDir, "README.md"), topReadme, "utf8");

  for (const arm of results) {
    const dir = join(args.outDir, arm.arm.milestone);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, "README.md"), folderReadme(arm.arm.milestone), "utf8");
    const stem = arm.arm.id;
    writeFileSync(join(dir, `${stem}.jsonl`), exportArmJsonl(arm), "utf8");
    if (args.csv) {
      writeFileSync(join(dir, `${stem}.csv`), exportArmCsv(arm), "utf8");
    }
  }

  const elapsed = ((Date.now() - started) / 1000).toFixed(1);
  console.log(`Wrote ${results.length} arms under ${args.outDir} in ${elapsed}s`);
}

main();
